ProductionWebMonitor/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.auth import views as auth_views

#patter url definitions
urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^restapi/', include('restapi.urls')),
    url(r'^webmonitor/', include('webmonitor.urls')),
    url(r'^startbootstrap/', include('startbootstrap.urls')),
    url(r'^accounts/login/$', auth_views.login),
    url(r'^accounts/logout/$', auth_views.logout, {'next_page': '/accounts/login'}),
    url(r'^i18n/', include('django.conf.urls.i18n')),
]

restapi/urls.py
from django.conf.urls import url
from rest_framework.urlpatterns import format_suffix_patterns
from . import views
from restapi.views import DownTimeReasonsFOGRequest, ProductionMachineRollupFOGRequest, VariableTrendFOGRequest, StatusRollupFOGRequest, MachineStatusFOGRequest, MachineVariableStatusFOGRequest, MachineKPIFOGRequest, JobOEEScatterFOGRequest, JobSummaryFOGRequest, ProductionSummaryFOGRequest

urlpatterns = [

    url(r'^company/$', views.CompanyList.as_view()),
    url(r'^company/(?P<pk>[0-9]+)/$', views.CompanyDetail.as_view()),
    url(r'^company$', views.CompanyListByParam.as_view()),
    url(r'^facilityextended/$', views.FacilityExtendedPost.as_view()),
    url(r'^facility/$', views.FacilityList.as_view()),
    url(r'^facility/(?P<pk>[0-9]+)/$', views.FacilityDetail.as_view()),
    url(r'^facility$', views.FacilityListByParam.as_view()),
    url(r'^plantextended/$', views.PlantExtendedPost.as_view()),
    url(r'^plant/$', views.PlantList.as_view()),
    url(r'^plant/(?P<pk>[0-9]+)/$', views.PlantDetail.as_view()),
    url(r'^plant$', views.PlantListByParam.as_view()),
    url(r'^reason/$', views.ReasonList.as_view()),
    url(r'^reason/(?P<pk>[0-9]+)/$', views.ReasonDetail.as_view()),
    url(r'^reason$', views.ReasonListByParam.as_view()),
    url(r'^machinegroupextended/$', views.MachineGroupExtendedPost.as_view()),
    url(r'^machinegroup/$', views.MachineGroupList.as_view()),
    url(r'^machinegroup/(?P<pk>[0-9]+)/$', views.MachineGroupDetail.as_view()),
    url(r'^machinegroup$', views.MachineGroupListByParam.as_view()),
    url(r'^machineextended/$', views.MachineExtendedPost.as_view()),
    url(r'^machine/$', views.MachineList.as_view()),
    url(r'^machine/(?P<pk>[0-9]+)/$', views.MachineDetail.as_view()),
    url(r'^machine$', views.MachineListByParam.as_view()),

    url(r'^list/$', views.RequestListView.as_view(), name = 'list'),
    url(r'^create/$', views.RequestCreateView.as_view(), name = 'create'),
    url(r'^(?P<pk>[-\w]+)/$', views.RequestDetailView.as_view(), name = 'detail'),

    url(r'^Request/DownTimeReasonsRequestFOG$', DownTimeReasonsFOGRequest.as_view(), name='downTimeReasonsRequestFOG'),
    url(r'^Request/ProductionMachineRollupRequestFOG$', ProductionMachineRollupFOGRequest.as_view(), name='productionMachineRollupFOG'),
    url(r'^Request/VariableTrendFOGRequest$', VariableTrendFOGRequest.as_view(), name='variableTrendFOGRequest'),
    url(r'^Request/StatusRollup$', StatusRollupFOGRequest.as_view(), name='statusRollupFOGRequest'),
    url(r'^Request/MachineStatusFOGRequest$', MachineStatusFOGRequest.as_view(), name='machineStatusFOGRequest'),
    url(r'^Request/MachineVariableStatusFOGRequest$', MachineVariableStatusFOGRequest.as_view(), name='machineVariableStatusFOGRequest'),
    url(r'^Request/MachineKPIFOGRequest$', MachineKPIFOGRequest.as_view(), name='machineKPIFOGRequest'),
    url(r'^Request/MachineJobScatterFOGRequest$', JobOEEScatterFOGRequest.as_view(), name='JobOEEScatterFOGRequest'),
    url(r'^Request/JobSummaryFOGRequest$', JobSummaryFOGRequest.as_view(), name='jobSummaryFOGRequest'),
    url(r'^Request/ProductionSummaryFOGRequest$', ProductionSummaryFOGRequest.as_view(), name='productionSummaryFOGRequest'),
]

urlpatterns = format_suffix_patterns(urlpatterns)

webmonitor/urls.py
from django.conf.urls import url
from . import views
from .views import ChartData

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^plants/(?P<plantId>[\w]+)/$', views.detail, name='detail'),

    # second iteration changes
    url(r'^reports/machine-status/$', views.report_machine_status, name='report-machinestatus'),
    url(r'^reports/downtime-reasons/$', views.report_downtime_reasons, name='report-downtimereasons'),
    url(r'^reports/production-rollup/$', views.report_production_rollup, name='report-productionrollup'),
    url(r'^reports/status-rollup/$', views.report_status_rollup, name='report-statusrollup'),
    url(r'^reports/variable-trend-rollup/$', views.report_variable_trend_rollup, name='report-variabletrendrollup'),
    url(r'^reports/dashboard/$', views.report_dashboard, name='report_dashboard'),

    url(r'^reports/create-custom-report/$', views.create_custom_report, name='create-custom-report'),

    url(r'^filters/plant/(?P<company_id>[\w]+)/(?P<site_id>[\w]+)/(?P<plant_id>[\w]+)/reasons/$',
        views.json_plant_reasons, name='json_plant_reasons'),

    # ajax filters
    url(r'^filters/model-tree-view/$', views.json_model_tree_view, name='json_model_tree_view'),
    url(r'^filters/company/(?P<company_id>[\w]+)/sites/$', views.json_sites, name='json_sites'),
    url(r'^filters/site/(?P<company_id>[\w]+)/(?P<site_id>[\w]+)/plants/$', views.json_plants, name='json_plants'),
    url(r'^filters/plant/(?P<company_id>[\w]+)/(?P<site_id>[\w]+)/(?P<plant_id>[\w]+)/machine_groups/$',
        views.json_machine_groups, name='json_machine_groups'),
    url(
        r'^filters/machine-group/(?P<company_id>[\w]+)/(?P<site_id>[\w]+)/(?P<plant_id>[\w]+)/(?P<machine_group_id>[\w]+)/machines/$',
        views.json_machines, name='json_machines'),

    url(r'^filters/custom/report/(?P<id>[0-9a-f-]+)', views.json_company_filter, name='json_company_filter'),

    # data json api
    url(r'^api/chart/data/$', ChartData.as_view(), name='api-data'),


]

webmonitor/models.py
import math
import uuid

from django.db import models
from django.core.urlresolvers import reverse
from django.utils import timezone
from django.contrib.auth.models import User
from django import forms


def one_day_hence():
    return timezone.now() + timezone.timedelta(days=-1)


class Company(models.Model):
    companyId = models.CharField(max_length=10)
    companyDescr = models.CharField(max_length=30)

    def __str__(self):
        return str(self.companyId) + ' - ' + str(self.companyDescr)


class Site(models.Model):
    company = models.ForeignKey(Company, on_delete=models.CASCADE)
    siteId = models.CharField(max_length=10)
    siteDescr = models.CharField(max_length=30)

    def __str__(self):
        return str(self.siteId) + ' - ' + str(self.siteDescr)


class Plant(models.Model):
    site = models.ForeignKey(Site, on_delete=models.CASCADE, null=True)
    plantId = models.CharField(max_length=10, null=True)
    plantDescr = models.CharField(max_length=30, null=True)
    endPointUrl = models.URLField(null=True)
    plantAlias = models.CharField(max_length=30, null=True)

    def __str__(self):
        return str(self.site.company.companyDescr) + ' - ' + str(self.site.siteDescr) + ' - ' + str(self.plantId) + ' - ' + str(self.plantDescr) + ' - ' + str(self.plantAlias)


class Reason(models.Model):
    plant = models.ForeignKey(Plant, on_delete=models.CASCADE)
    reasonId = models.CharField(max_length=10)
    reasonDescr = models.CharField(max_length=30)

    def __str__(self):
        return str(self.reasonId) + ' - ' + str(self.reasonDescr)

class Shift(models.Model):
    plant = models.ForeignKey(Plant, on_delete=models.CASCADE)
    shiftId = models.CharField(max_length=10)
    shiftDescr = models.CharField(max_length=30)
    startTime = models.TimeField()
    endTime = models.TimeField()

    def __str__(self):
        return str(self.plant.plantId) + ' - ' + str(self.shiftId) + ' - ' + str(self.shiftDescr)

class MachineGroup(models.Model):
    plant = models.ForeignKey(Plant, on_delete=models.CASCADE)
    machineGroupId = models.CharField(max_length=10)
    machineGroupDescr = models.CharField(max_length=30)
    machineGroupAlias = models.CharField(max_length=30, null=True)

    def __str__(self):
        return str(self.plant.site.company.companyId) + ' - ' + str(self.plant.site.siteId) + ' - ' + str(self.plant.plantId) + ' - ' + str(self.machineGroupId) + ' - ' + str(self.machineGroupDescr) + ' - ' + str(self.machineGroupAlias)


class Machine(models.Model):
    machineGroup = models.ForeignKey(MachineGroup, on_delete=models.CASCADE, null=True)
    machineId = models.CharField(max_length=10, null=True)
    machineDescr = models.CharField(max_length=30, null=True)
    machineAlias = models.CharField(max_length=30, null=True)

    def __str__(self):
        return str(self.machineGroup.plant.site.company.companyId) + ' - ' + str(
            self.machineGroup.plant.site.siteId) + ' - ' + str(self.machineGroup.plant.plantId) + ' - ' + str(
            self.machineGroup.machineGroupId) + ' - ' + str(self.machineId) + ' - ' + str(self.machineDescr) + ' - ' + str(self.machineAlias)

class Calendar(models.Model):
    machine = models.ForeignKey(Machine, on_delete=models.CASCADE, null=True)
    year = models.IntegerField()
    month = models.IntegerField()

    def __str__(self):
        return str(self.machine.MacchineId) + ' - ' + str(self.year) + ' - ' + str(self.month)

class LaborDay(models.Model):
    calendar = models.ForeignKey(Calendar, on_delete=models.CASCADE, null=True)
    shift = models.ForeignKey(Shift, on_delete=models.CASCADE, null=True)
    date = models.DateField()

    def __str__(self):
        return str(self.calendar.machine.machineId) + ' - ' + str(self.date) + ' - ' + str(self.shift.shiftDescr)

class MachineHistoricalEventInterval(models.Model):
    machine = models.ForeignKey(Machine, on_delete=models.CASCADE)
    fromDate = models.DateField()
    toDate = models.DateField()


class MachineHistoricalEvent(models.Model):
    interval = models.ForeignKey(MachineHistoricalEventInterval, on_delete=models.CASCADE)
    status = models.CharField(max_length=20)
    startDttm = models.DateTimeField()
    endDttm = models.DateTimeField()
    duration = models.FloatField()
    reason = models.CharField(max_length=10)


class MachineDownTimeReasonInterval(models.Model):
    machine = models.ForeignKey(Machine, on_delete=models.CASCADE)
    fromDate = models.DateField()
    toDate = models.DateField()


class MachineDownTimeReason(models.Model):
    interval = models.ForeignKey(MachineHistoricalEventInterval, on_delete=models.CASCADE)
    reason = models.CharField(max_length=10)
    reasonDescr = models.CharField(max_length=30)
    ocurrences = models.IntegerField()
    # Este es el valor absoluto expresado en minutos
    duration = models.FloatField()
    # Esta es la representacion de la duración en el formato dd:hh:mm:ss
    durationFormated = models.CharField(max_length=12)
    # Este es el valor absoluto expresado en minutos
    avgDuration = models.FloatField()
    # Esta es la representacion del promedio de duración en el formato dd:hh:mm:ss
    avgDurationFormated = models.CharField(max_length=12)
    intervalPorcentualValue = models.FloatField()

    def getFormatTime(minutesIn):
        if minutesIn < 1440:
            daysAux = 0
        else:
            fraction, daysAux = math.modf(minutesIn / 1440)

        if minutesIn - (daysAux * 1440) < 60:
            hoursAux = 0
        else:
            fraction, hoursAux = math.modf((minutesIn - (daysAux * 1440)) / 60)

        minutesAux = minutesIn - (daysAux * 1440) - (hoursAux * 60)

        return str(daysAux) + ':' + str(hoursAux) + ':' + str(minutesAux)

    def save(self):
        self.durationFormated = self.getFormatTime(self.duration)
        self.avgDurationFormated = self.getFormatTime(self.avgDuration)
        super(MachineDownTimeReason, self).save()


class MachineHistorialEventsRollOutRequest(models.Model):
    fromDate = models.DateField(default=one_day_hence)
    toDate = models.DateField(default=timezone.now)
    plantId = models.CharField(max_length=10)

    def get_absolute_url(self):
        return reverse('favorite', kwargs={'pk': self.pk})

    def __str__(self):
        return self.plantId


# Reporting models
class UserData(models.Model):
    user = models.ForeignKey(User, editable=False)

    class Meta:
        abstract = True


class ReportCategory(models.Model):
    categoryId = models.CharField(max_length=10)
    categoryDescr = models.CharField(max_length=30)

    def __str__(self):
        return str(self.categoryId) + ' - ' + str(self.categoryDescr)


class Report(models.Model):
    category = models.ForeignKey(ReportCategory, on_delete=models.CASCADE)
    reportId = models.CharField(max_length=10)
    reportDescr = models.CharField(max_length=50)
    reportBlockName = models.CharField(max_length=50)
    reportFunctionName = models.CharField(max_length=50)
    maxDaysWindow = models.IntegerField(default=0)
    uriIcon = models.CharField(max_length=100, blank=True, null=True)
    tooltipDecr = models.CharField(max_length=100, blank=True, null=True)

    class Meta:
        permissions = (
            ('view_report_machine_status', 'View report machine status'),
            ('view_report_downtime_reasons', 'View report downtime reasons'),
            ('view_report_production_rollup', 'View report production rollup'),
            ('view_report_status_rollup', 'View report status rollup'),
            ('view_report_var_trend_rollup', 'View report var. trend rollup'),
        )

    def __str__(self):
        return str(self.reportId) + ' - ' + str(self.reportDescr)

class ReportUser(models.Model):
    user = models.ForeignKey(User)
    reports = models.ManyToManyField(Report)

    def __str__(self):
        return str(self.user)

class ReportVariable(models.Model):
    report = models.ForeignKey(Report, on_delete=models.CASCADE, null=True)
    variableId = models.CharField(max_length=10, null=True)
    variableDescr = models.CharField(max_length=30, null=True)

    def __str__(self):
        return str(self.variableId) + ' - ' + str(self.variableDescr)

class CustomReport(UserData):
    user = models.ForeignKey(User)
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    name = models.CharField(max_length=60)
    minFlag = models.CharField(max_length=1, default='N')
    maxFlag = models.CharField(max_length=1, default='N')
    avgFlag = models.CharField(max_length=1, default='N')
    trendFlag = models.CharField(max_length=1, default='N')
    fechaFinalFijaFlag = models.CharField(max_length=1, default='N')
    fechaFinal = models.DateField(blank=True, null=True)
    horaFinal = models.TimeField(blank=True, null=True, default='23:59')
    diasComputablesFechaFinal = models.CharField(max_length=4, blank=True, null=True)
    fechaInicialFijaFlag = models.CharField(max_length=1, default='N')
    fechaInicial = models.DateField(blank=True, null=True)
    horaInicial = models.TimeField(blank=True, null=True, default='00:01')
    diasComputablesFechaInicial = models.CharField(max_length=4, blank=True, null=True)
    fechaActual = models.CharField(max_length=1, default='N')
    semanaAnterior = models.CharField(max_length=1, default='N')
    semanaActual = models.CharField(max_length=1, default='N')
    mesAnterior = models.CharField(max_length=1, default='N')
    mesActual = models.CharField(max_length=1, default='N')
    widgetSize = models.CharField(max_length=10, blank=True, null=True)
    monitorFlag = models.CharField(max_length=1, default='N', null=True)
    hour = models.CharField(max_length=1, default='N', null=True)
    day = models.CharField(max_length=1, default='N', null=True)
    week = models.CharField(max_length=1, default='N', null=True)
    month = models.CharField(max_length=1, default='N', null=True)

    def __str__(self):

webmonitor/forms.py
from django import forms
from webmonitor.models import Report


class CustomReportForm(forms.Form):
    report = forms.ModelChoiceField(queryset=Report.objects.all(), label=u'report')
    customReportDescr = forms.CharField(label='Name or Description', max_length=100)

webmonitor/templates/baselp.html
{% load staticfiles %}
{% load i18n %}
<!DOCTYPE html>
<html lang="en">
<head lang="{{LANGUAGE_CODE}}">
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    {% trans "Ajover production monitor" as the_title %}
    <title>{% block title %}{{ the_title }}{% endblock %}</title>

    <!-- Bootstrap -->
    <link rel="stylesheet" type="text/css"
          href="https://fonts.googleapis.com/css?family=Raleway|PT+Sans|Open+Sans|Cabin">
    <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet"/>
    <link href="{% static 'css/style_login.css' %}" rel="stylesheet"/>

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
    {% block head %}
    {% endblock %}
</head>
<body>
{% block main-content %}
{% endblock %}
<!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
<!-- Include all compiled plugins (below), or include individual files as needed -->
<script src="{% static 'vendor/bootstrap/js/bootstrap.min.js' %}"></script>
{% block scripts %}
{% endblock %}
</body>
</html>

webmonitor/templates/machine_status_template.html
<div class="row template">
            <div class="panel panel-default">
                    <div class="panel-body" id="machine-panel">
                    </div>
            </div>
        </div>

webmonitor/templates/my_custom_reports.html
<div class="row">
    <div class="col-lg-12">
        <div class="panel panel-info">
            <div class="panel-heading">
                <h3 class="panel-title collapse-filter"><a data-toggle="collapse" href="#filter-collapse"
                                                           aria-expanded="true" aria-controls="filter-collapse"
                                                           class="btn-block">Custom Reports</a></h3>
                <span class="pull-right"><i class="fa fa-chevron-up" aria-hidden="true"></i></span>
            </div>
            <div id="filter-collapse" class="panel-collapse collapse in">
                <div class="panel-body">
                    <form action="" method="get" accept-charset="utf-8" class="form-inline">
                        <div class="form-group">
                            <label for="custom-report">Custom report</label>
                            <select class="form-control" id="custom-report">
                                <option selected>Choose...</option>
                                {% for custom_report in custom_report_list %}
                                <option value="{{ custom_report.customReportId}}">{{ custom_report.customReportDescr}}
                                </option>
                                {% endfor %}
                            </select>
                        </div>
                        <div class="form-group">
                            <button type="submit" class="btn btn-primary">Load</button>
                        </div>
                        <div class="form-group">
                            <button type="submit" class="btn btn-primary">New</button>
                        </div>
                        <div class="form-group">
                            <label for="formGroupExampleInput2">Name</label>
                            <input type="text" class="form-control" id="formGroupExampleInput2"
                                   placeholder="Another input">
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

webmonitor/templates/my_reporting_filters.bak.html
<form action="" method="get" accept-charset="utf-8">
    <div class="row">
        <fieldset>
            <legend>company</legend>
            {% for company in company_list %}
            <div class="checkbox checkbox-inline">
                <input type="checkbox" id="company-{{ company.companyId}}" value="{{ company.companyId}}"
                       name="cbx-company"/>
                <label for="company-{{ company.companyId}}">{{ company.companyDescr }}</label>
            </div>
            {% endfor %}
        </fieldset>
    </div>
    <div class="row">
        <fieldset>
            <legend>Site</legend>
            <div id="site">
            </div>
        </fieldset>
    </div>
    <div class="row">
        <fieldset>
            <legend>Plant</legend>
            <div id="plant">
            </div>
    </div>
    <div class="row">
        <fieldset>
            <legend>Machine group</legend>
            <div id="machine-group">
            </div>
        </fieldset>
    </div>
    <div class="row">
        <fieldset>
            <legend>Machines</legend>
            <div id="machine" name = "machine">
            </div>
        </fieldset>
    </div>
	<div class="row">
	<div class="form-group">
		<label for="startDttm">Start date:</label>
		<input type="date" class="form-control" id="startDttm" name = "startDttm">
	</div>
	<div class="form-group">
		<label for="endDttm">End date</label>
		<input type="date" class="form-control" id="endDttm" name = "endDttm">
	</div>
	</div>
</form>
<script>
var classAttribute;
  $(document).ready(
    function() {
      /* Company is selected */
      $("input[name='cbx-company']").change(function() {
        //console.log($(this).val() + " › " + $(this).is(':checked'));
        if ($(this).is(':checked')) {
          var company_id = $(this).val();
          var url = "/webmonitor/filters/company/" + company_id + "/sites/";

          $.getJSON(url, function(sites) {
            var options = '';
            for (var i = 0; i < sites.length; i++) {
              options += '<div class="checkbox checkbox-inline">';
              options += '<input type="checkbox" id="site-' + sites[i].fields['siteId'] + '" value="' + sites[i].fields['siteId'] + '" name="cbx-site" class="' + company_id + '.' + sites[i].fields['siteId'] + '"/>';
              options += '<label for="site-' + sites[i].fields['siteId'] + '" class = "' + company_id + '.' + sites[i].fields['siteId'] + '">' + sites[i].fields['siteDescr'] + '</label>';
              options += '</div>';
              classAttribute = company_id + '.' + sites[i].fields['siteId'];
            }
            $("#site").append(options);
            //$("select#site option:first").attr('selected', 'selected');
            //$("select#site").attr('disabled', false);
          });
        } else {
          console.log("remove company");
          $('input[class="' + $(this).val() + '"]').remove();
          $('label[class="' + $(this).val() + '"]').remove();
        }
      });

      /* Site is selected */
      $("#site").on("change", "input[type=checkbox]", function() {
        //console.log($(this).val() + " › " + $(this).is(':checked'));
        if ($(this).is(':checked')) {
          var site_id = $(this).val();
          var url = "/webmonitor/filters/site/" + site_id + "/plants/";

          $.getJSON(url, function(plants) {
            var options = '';
            for (var i = 0; i < plants.length; i++) {
              options += '<div class="checkbox checkbox-inline">';
              options += '<input type="checkbox" id="plant-' + plants[i].fields['plantId'] + '" value="' + plants[i].fields['plantId'] + '" name="cbx-plant" class="' + classAttribute + '.' + plants[i].fields['plantId'] + '">';
              options += '<label for="plant-' + plants[i].fields['plantId'] + '" class = "' + classAttribute + '.' + plants[i].fields['plantId'] + '">' + plants[i].fields['plantDescr'] + '</label>';
              classAttribute = classAttribute + '.' + plants[i].fields['plantId'];
              options += '</div>';
            }
            $("#plant").append(options);
            //$("select#site option:first").attr('selected', 'selected');
            //$("select#site").attr('disabled', false);
          });
        } else {
          console.log("remove sites");
          $('input[class="' + $(this).val() + '"]').remove();
          $('label[class="' + $(this).val() + '"]').remove();
        }
      });

      /* Plant is selected */
      $("#plant").on("change", "input[type=checkbox]", function() {
        //console.log($(this).val() + " › " + $(this).is(':checked'));
        if ($(this).is(':checked')) {
          var plant_id = $(this).val();
          var url = "/webmonitor/filters/plant/" + plant_id + "/machine_groups/";

          $.getJSON(url, function(machine_groups) {
            var options = '';
            for (var i = 0; i < machine_groups.length; i++) {
              options += '<div class="checkbox checkbox-inline">';
              options += '<input type="checkbox" id="machine-group-' + machine_groups[i].fields['machineGroupId'] + '" value="' + machine_groups[i].fields['machineGroupId'] + '" name="cbx-machine-group" class="' + classAttribute + '.' + machine_groups[i].fields['machineGroupId'] + '">';
              options += '<label for="machine-group-' + machine_groups[i].fields['machineGroupId'] + '" class = "' + classAttribute + '.' + machine_groups[i].fields['machineGroupId'] + '">' + machine_groups[i].fields['machineGroupDescr'] + '</label>';
              classAttribute = classAttribute + '.' + machine_groups[i].fields['machineGroupId'];
              options += '</div>';
            }
            $("#machine-group").append(options);
            //$("select#plant option:first").attr('selected', 'selected');
            //$("select#plant").attr('disabled', false);
          });
        } else {
          console.log("remove machine groups");
          $('input[class="' + $(this).val() + '"]').remove();
          $('label[class="' + $(this).val() + '"]').remove();
        }
      });

      /* machine group is selected */
      $("#machine-group").on("change", "input[type=checkbox]", function() {
        //console.log($(this).val() + " › " + $(this).is(':checked'));
        if ($(this).is(':checked')) {
          var machine_group_id = $(this).val();
          var url = "/webmonitor/filters/machine-group/" + machine_group_id + "/machines/";

          $.getJSON(url, function(machines) {
            var options = '';
            for (var i = 0; i < machines.length; i++) {
              options += '<div class="checkbox checkbox-inline ' + machine_group_id + '">';
              options += '<input type="checkbox" name = "machine" id="machine-' + machines[i]['machineId'] + '" value="' + machines[i]['machineId'] + '" name="cbx-machine" class="' +machines[i]['class'] + '">';
              options += '<label for="machine-' + machines[i]['machineId'] + '" class = "' + classAttribute + '.' + machines[i]['machineId'] + '">' + machines[i]['machineDescr'] + '</label>';

              options += '</div>';
            }
            $("#machine").append(options);
            //$("select#machine option:first").attr('selected', 'selected');
            //$("select#machine").attr('disabled', false);
          });
        } else {
          console.log("remove machine groups");
          $('input[class="' + $(this).val() + '"]').remove();
          $('label[class="' + $(this).val() + '"]').remove();
        }
      });

      /* machine selected */
      $("#machine").on("change", "input[type=checkbox]", function() {
        console.log($(this).val() + " › " + $(this).is(':checked'));
        if ($(this).is(':checked')) {
          console.log("Get report for: " + $(this).val());
        } else {

        }
      });
    });

</script>

webmonitor/templates/variable_trend_rollup_template.html
<div class="row template">
                <div class="panel panel-default">
                    <div class="panel-body">
                        <div id='chart'></div>
                    </div>
                </div>
        </div>