ProductionWebMonitor/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.auth import views as auth_views

#patter url definitions
urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^restapi/', include('restapi.urls')),
    url(r'^webmonitor/', include('webmonitor.urls')),
    url(r'^startbootstrap/', include('startbootstrap.urls')),
    url(r'^accounts/login/$', auth_views.login),
    url(r'^accounts/logout/$', auth_views.logout, {'next_page': '/accounts/login'}),
    url(r'^i18n/', include('django.conf.urls.i18n')),
]

restapi/urls.py
from django.conf.urls import url
from rest_framework.urlpatterns import format_suffix_patterns
from . import views
from restapi.views import DownTimeReasonsFOGRequest, ProductionMachineRollupFOGRequest, VariableTrendFOGRequest, StatusRollupFOGRequest, MachineStatusFOGRequest, MachineVariableStatusFOGRequest, MachineKPIFOGRequest, JobOEEScatterFOGRequest, JobSummaryFOGRequest, ProductionSummaryFOGRequest

urlpatterns = [

    url(r'^company/$', views.CompanyList.as_view()),
    url(r'^company/(?P<pk>[0-9]+)/$', views.CompanyDetail.as_view()),
    url(r'^company$', views.CompanyListByParam.as_view()),
    url(r'^facilityextended/$', views.FacilityExtendedPost.as_view()),
    url(r'^facility/$', views.FacilityList.as_view()),
    url(r'^facility/(?P<pk>[0-9]+)/$', views.FacilityDetail.as_view()),
    url(r'^facility$', views.FacilityListByParam.as_view()),
    url(r'^plantextended/$', views.PlantExtendedPost.as_view()),
    url(r'^plant/$', views.PlantList.as_view()),
    url(r'^plant/(?P<pk>[0-9]+)/$', views.PlantDetail.as_view()),
    url(r'^plant$', views.PlantListByParam.as_view()),
    url(r'^reason/$', views.ReasonList.as_view()),
    url(r'^reason/(?P<pk>[0-9]+)/$', views.ReasonDetail.as_view()),
    url(r'^reason$', views.ReasonListByParam.as_view()),
    url(r'^machinegroupextended/$', views.MachineGroupExtendedPost.as_view()),
    url(r'^machinegroup/$', views.MachineGroupList.as_view()),
    url(r'^machinegroup/(?P<pk>[0-9]+)/$', views.MachineGroupDetail.as_view()),
    url(r'^machinegroup$', views.MachineGroupListByParam.as_view()),
    url(r'^machineextended/$', views.MachineExtendedPost.as_view()),
    url(r'^machine/$', views.MachineList.as_view()),
    url(r'^machine/(?P<pk>[0-9]+)/$', views.MachineDetail.as_view()),
    url(r'^machine$', views.MachineListByParam.as_view()),

    url(r'^list/$', views.RequestListView.as_view(), name = 'list'),
    url(r'^create/$', views.RequestCreateView.as_view(), name = 'create'),
    url(r'^(?P<pk>[-\w]+)/$', views.RequestDetailView.as_view(), name = 'detail'),

    url(r'^Request/DownTimeReasonsRequestFOG$', DownTimeReasonsFOGRequest.as_view(), name='downTimeReasonsRequestFOG'),
    url(r'^Request/ProductionMachineRollupRequestFOG$', ProductionMachineRollupFOGRequest.as_view(), name='productionMachineRollupFOG'),
    url(r'^Request/VariableTrendFOGRequest$', VariableTrendFOGRequest.as_view(), name='variableTrendFOGRequest'),
    url(r'^Request/StatusRollup$', StatusRollupFOGRequest.as_view(), name='statusRollupFOGRequest'),
    url(r'^Request/MachineStatusFOGRequest$', MachineStatusFOGRequest.as_view(), name='machineStatusFOGRequest'),
    url(r'^Request/MachineVariableStatusFOGRequest$', MachineVariableStatusFOGRequest.as_view(), name='machineVariableStatusFOGRequest'),
    url(r'^Request/MachineKPIFOGRequest$', MachineKPIFOGRequest.as_view(), name='machineKPIFOGRequest'),
    url(r'^Request/MachineJobScatterFOGRequest$', JobOEEScatterFOGRequest.as_view(), name='JobOEEScatterFOGRequest'),
    url(r'^Request/JobSummaryFOGRequest$', JobSummaryFOGRequest.as_view(), name='jobSummaryFOGRequest'),
    url(r'^Request/ProductionSummaryFOGRequest$', ProductionSummaryFOGRequest.as_view(), name='productionSummaryFOGRequest'),
]

urlpatterns = format_suffix_patterns(urlpatterns)

startbootstrap/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^index/$', views.index, name='index'),
    url(r'^dashboard$', views.widget_main, name='dashboard'),
    url(r'^widgets/render-widget$', views.render_widget, name='render_widget'),
]

startbootstrap/models.py
from django.db import models

# Create your models here.

webmonitor/models.py
import math
import uuid

from django.db import models
from django.core.urlresolvers import reverse
from django.utils import timezone
from django.contrib.auth.models import User
from django import forms


def one_day_hence():
    return timezone.now() + timezone.timedelta(days=-1)


class Company(models.Model):
    companyId = models.CharField(max_length=10)
    companyDescr = models.CharField(max_length=30)

    def __str__(self):
        return str(self.companyId) + ' - ' + str(self.companyDescr)


class Site(models.Model):
    company = models.ForeignKey(Company, on_delete=models.CASCADE)
    siteId = models.CharField(max_length=10)
    siteDescr = models.CharField(max_length=30)

    def __str__(self):
        return str(self.siteId) + ' - ' + str(self.siteDescr)


class Plant(models.Model):
    site = models.ForeignKey(Site, on_delete=models.CASCADE, null=True)
    plantId = models.CharField(max_length=10, null=True)
    plantDescr = models.CharField(max_length=30, null=True)
    endPointUrl = models.URLField(null=True)
    plantAlias = models.CharField(max_length=30, null=True)

    def __str__(self):
        return str(self.site.company.companyDescr) + ' - ' + str(self.site.siteDescr) + ' - ' + str(self.plantId) + ' - ' + str(self.plantDescr) + ' - ' + str(self.plantAlias)


class Reason(models.Model):
    plant = models.ForeignKey(Plant, on_delete=models.CASCADE)
    reasonId = models.CharField(max_length=10)
    reasonDescr = models.CharField(max_length=30)

    def __str__(self):
        return str(self.reasonId) + ' - ' + str(self.reasonDescr)

class Shift(models.Model):
    plant = models.ForeignKey(Plant, on_delete=models.CASCADE)
    shiftId = models.CharField(max_length=10)
    shiftDescr = models.CharField(max_length=30)
    startTime = models.TimeField()
    endTime = models.TimeField()

    def __str__(self):
        return str(self.plant.plantId) + ' - ' + str(self.shiftId) + ' - ' + str(self.shiftDescr)

class MachineGroup(models.Model):
    plant = models.ForeignKey(Plant, on_delete=models.CASCADE)
    machineGroupId = models.CharField(max_length=10)
    machineGroupDescr = models.CharField(max_length=30)
    machineGroupAlias = models.CharField(max_length=30, null=True)

    def __str__(self):
        return str(self.plant.site.company.companyId) + ' - ' + str(self.plant.site.siteId) + ' - ' + str(self.plant.plantId) + ' - ' + str(self.machineGroupId) + ' - ' + str(self.machineGroupDescr) + ' - ' + str(self.machineGroupAlias)


class Machine(models.Model):
    machineGroup = models.ForeignKey(MachineGroup, on_delete=models.CASCADE, null=True)
    machineId = models.CharField(max_length=10, null=True)
    machineDescr = models.CharField(max_length=30, null=True)
    machineAlias = models.CharField(max_length=30, null=True)

    def __str__(self):
        return str(self.machineGroup.plant.site.company.companyId) + ' - ' + str(
            self.machineGroup.plant.site.siteId) + ' - ' + str(self.machineGroup.plant.plantId) + ' - ' + str(
            self.machineGroup.machineGroupId) + ' - ' + str(self.machineId) + ' - ' + str(self.machineDescr) + ' - ' + str(self.machineAlias)

class Calendar(models.Model):
    machine = models.ForeignKey(Machine, on_delete=models.CASCADE, null=True)
    year = models.IntegerField()
    month = models.IntegerField()

    def __str__(self):
        return str(self.machine.MacchineId) + ' - ' + str(self.year) + ' - ' + str(self.month)

class LaborDay(models.Model):
    calendar = models.ForeignKey(Calendar, on_delete=models.CASCADE, null=True)
    shift = models.ForeignKey(Shift, on_delete=models.CASCADE, null=True)
    date = models.DateField()

    def __str__(self):
        return str(self.calendar.machine.machineId) + ' - ' + str(self.date) + ' - ' + str(self.shift.shiftDescr)

class MachineHistoricalEventInterval(models.Model):
    machine = models.ForeignKey(Machine, on_delete=models.CASCADE)
    fromDate = models.DateField()
    toDate = models.DateField()


class MachineHistoricalEvent(models.Model):
    interval = models.ForeignKey(MachineHistoricalEventInterval, on_delete=models.CASCADE)
    status = models.CharField(max_length=20)
    startDttm = models.DateTimeField()
    endDttm = models.DateTimeField()
    duration = models.FloatField()
    reason = models.CharField(max_length=10)


class MachineDownTimeReasonInterval(models.Model):
    machine = models.ForeignKey(Machine, on_delete=models.CASCADE)
    fromDate = models.DateField()
    toDate = models.DateField()


class MachineDownTimeReason(models.Model):
    interval = models.ForeignKey(MachineHistoricalEventInterval, on_delete=models.CASCADE)
    reason = models.CharField(max_length=10)
    reasonDescr = models.CharField(max_length=30)
    ocurrences = models.IntegerField()
    # Este es el valor absoluto expresado en minutos
    duration = models.FloatField()
    # Esta es la representacion de la duración en el formato dd:hh:mm:ss
    durationFormated = models.CharField(max_length=12)
    # Este es el valor absoluto expresado en minutos
    avgDuration = models.FloatField()
    # Esta es la representacion del promedio de duración en el formato dd:hh:mm:ss
    avgDurationFormated = models.CharField(max_length=12)
    intervalPorcentualValue = models.FloatField()

    def getFormatTime(minutesIn):
        if minutesIn < 1440:
            daysAux = 0
        else:
            fraction, daysAux = math.modf(minutesIn / 1440)

        if minutesIn - (daysAux * 1440) < 60:
            hoursAux = 0
        else:
            fraction, hoursAux = math.modf((minutesIn - (daysAux * 1440)) / 60)

        minutesAux = minutesIn - (daysAux * 1440) - (hoursAux * 60)

        return str(daysAux) + ':' + str(hoursAux) + ':' + str(minutesAux)

    def save(self):
        self.durationFormated = self.getFormatTime(self.duration)
        self.avgDurationFormated = self.getFormatTime(self.avgDuration)
        super(MachineDownTimeReason, self).save()


class MachineHistorialEventsRollOutRequest(models.Model):
    fromDate = models.DateField(default=one_day_hence)
    toDate = models.DateField(default=timezone.now)
    plantId = models.CharField(max_length=10)

    def get_absolute_url(self):
        return reverse('favorite', kwargs={'pk': self.pk})

    def __str__(self):
        return self.plantId


# Reporting models
class UserData(models.Model):
    user = models.ForeignKey(User, editable=False)

    class Meta:
        abstract = True


class ReportCategory(models.Model):
    categoryId = models.CharField(max_length=10)
    categoryDescr = models.CharField(max_length=30)

    def __str__(self):
        return str(self.categoryId) + ' - ' + str(self.categoryDescr)


class Report(models.Model):
    category = models.ForeignKey(ReportCategory, on_delete=models.CASCADE)
    reportId = models.CharField(max_length=10)
    reportDescr = models.CharField(max_length=50)
    reportBlockName = models.CharField(max_length=50)
    reportFunctionName = models.CharField(max_length=50)
    maxDaysWindow = models.IntegerField(default=0)
    uriIcon = models.CharField(max_length=100, blank=True, null=True)
    tooltipDecr = models.CharField(max_length=100, blank=True, null=True)

    class Meta:
        permissions = (
            ('view_report_machine_status', 'View report machine status'),
            ('view_report_downtime_reasons', 'View report downtime reasons'),
            ('view_report_production_rollup', 'View report production rollup'),
            ('view_report_status_rollup', 'View report status rollup'),
            ('view_report_var_trend_rollup', 'View report var. trend rollup'),
        )

    def __str__(self):
        return str(self.reportId) + ' - ' + str(self.reportDescr)

class ReportUser(models.Model):
    user = models.ForeignKey(User)
    reports = models.ManyToManyField(Report)

    def __str__(self):
        return str(self.user)

class ReportVariable(models.Model):
    report = models.ForeignKey(Report, on_delete=models.CASCADE, null=True)
    variableId = models.CharField(max_length=10, null=True)
    variableDescr = models.CharField(max_length=30, null=True)

    def __str__(self):
        return str(self.variableId) + ' - ' + str(self.variableDescr)

class CustomReport(UserData):
    user = models.ForeignKey(User)
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    name = models.CharField(max_length=60)
    minFlag = models.CharField(max_length=1, default='N')
    maxFlag = models.CharField(max_length=1, default='N')
    avgFlag = models.CharField(max_length=1, default='N')
    trendFlag = models.CharField(max_length=1, default='N')
    fechaFinalFijaFlag = models.CharField(max_length=1, default='N')
    fechaFinal = models.DateField(blank=True, null=True)
    horaFinal = models.TimeField(blank=True, null=True, default='23:59')
    diasComputablesFechaFinal = models.CharField(max_length=4, blank=True, null=True)
    fechaInicialFijaFlag = models.CharField(max_length=1, default='N')
    fechaInicial = models.DateField(blank=True, null=True)
    horaInicial = models.TimeField(blank=True, null=True, default='00:01')
    diasComputablesFechaInicial = models.CharField(max_length=4, blank=True, null=True)
    fechaActual = models.CharField(max_length=1, default='N')
    semanaAnterior = models.CharField(max_length=1, default='N')
    semanaActual = models.CharField(max_length=1, default='N')
    mesAnterior = models.CharField(max_length=1, default='N')
    mesActual = models.CharField(max_length=1, default='N')
    widgetSize = models.CharField(max_length=10, blank=True, null=True)
    monitorFlag = models.CharField(max_length=1, default='N', null=True)
    hour = models.CharField(max_length=1, default='N', null=True)
    day = models.CharField(max_length=1, default='N', null=True)
    week = models.CharField(max_length=1, default='N', null=True)
    month = models.CharField(max_length=1, default='N', null=True)

    def __str__(self):

startbootstrap/views.py
from django.http import HttpResponse
from django.template.loader import render_to_string

from webmonitor.models import *
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from django.core.urlresolvers import resolve

@login_required
def index(request):
    reports = Report.objects.all()
    context = {
        'reports': reports
    }
    return render(request, 'index.html', context)

@login_required
def widget_main(request):
    query = ''
    reportId = request.GET['reportId']
    if reportId == 'none':
        if CustomReport.objects.filter(user__username=request.user.username, name='Last Query').exists():
            query = CustomReport.objects.get(user__username=request.user.username, name='Last Query').id
        else:
            query = 'none'
    else:
        query = reportId
    reports_user = ReportUser.objects.all().get(user__username=request.user.username)
    reports = reports_user.reports.all()
    categoryList = []
    for i in reports:
        categoryAux = i.category
        if categoryAux not in categoryList:
            categoryList.append(categoryAux)

    custom_report_list = CustomReport.objects.filter(user__username=request.user.username)
    company_list = []
    machine_user = MachineUser.objects.all().get(user__username=request.user.username)
    company_list_def = machine_user.machine.all()
    for i in company_list_def:
        company_str = i.machineGroup.plant.site.company.companyId
        find_tmp = False
        for j in company_list:
            if j.machineGroup.plant.site.company.companyId == company_str:
                find_tmp = True
        if find_tmp == False:
            company_list.append(i)
    context = {
        'reports': reports,
        'categoryList': categoryList,
        'custom_report_list': custom_report_list,
        'company_list': company_list,
        'query': query
    }
    return render(request, 'widget_main.html', context)

def render_widget(request):
    reportId = request.GET['reportId']
    print(reportId)
    report = Report.objects.all().get(reportId=reportId)
    html = render_to_string(report.reportBlockName)
    return HttpResponse(html)
    #return render(request, report.reportBlockName)

startbootstrap/templates/calendar_template.html
{% load i18n %}
<form action="" method="" id="custom-report-form" accept-charset="utf-8">
    {% csrf_token %}
    {% trans "# Days from now" as days_from %}
    <div class="row">
        <div class="col-md-6">
            <label for="startDttm">{% trans "Start Date:" %}</label>
            <input type="date" class="form-control" id="startDttm" name="startDttm" value="{{fromDate|date:"Y-m-d" }}">
            <label for="startTime">{% trans "Start Time:" %}</label>
            <input type="time" class="form-control" id="startTime" name="startTime" value="">
            <br/>
            <label for="start-num-days">{{ days_from }}</label>
            <input type="number" class="form-control" id="start-num-days" placeholder="{{ days_from }}"/>
        </div>
        <div class="col-md-6">
            <label for="endDttm">{% trans "End Date:" %}</label>
            <input type="date" class="form-control" id="endDttm" name="endDttm" value="{{toDate|date:"Y-m-d" }}">
            <label for="endTime">{% trans "End Time:" %}</label>
            <input type="time" class="form-control" id="endTime" name="endTime" value="">
            <br/>
            <label for="end-num-days">{{ days_from }}</label>
            <input type="number" class="form-control" id="end-num-days" placeholder="{{ days_from }}"/>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
            <br/>
            <button id="today" value="N" type="button" class="btn btn-secondary">{% trans "Today" %}</button>
            <button id="lastweek" value="N" type="button" class="btn btn-secondary">{% trans "Last Week" %}</button>
            <button id="thisweek" value="N" type="button" class="btn btn-secondary">{% trans "This week" %}</button>
            <button id="lastmonth" value="N" type="button" class="btn btn-secondary">{% trans "Last Month" %}</button>
            <button id="thismonth" value="N" type="button" class="btn btn-secondary">{% trans "This Month" %}</button>
        </div>
    </div>
    <div class="row">
        <div id="widget-size">
            <legend>Period</legend>
            <div class="col-md-12">
                <label><input type="radio" name="optradio" value="hour" id="hour">{% trans "Hour" %}</label>
                <label><input type="radio" name="optradio" value="day" id="day">{% trans "Day" %}</label>
                <label><input type="radio" name="optradio" value="week" id="week">{% trans "Week" %}</label>
                <label><input type="radio" name="optradio" value="month" id="month">{% trans "Month" %}</label>
            </div>
        </div>
    </div>
</form>

startbootstrap/templates/category_widget_list.html
<div class="col-lg-12">
            <fieldset>
                {% for i in report_list %}
                    <div class="col-lg-10 widget-option checkbox checkbox-info checkbox-circle">
                        <input type="hidden" class="report" value="{{ i.reportId }}"/>
                        <input type="hidden" class="function" value="{{ i.reportFunctionName }}"/>
                        <input type="hidden" class="tooltip-text" value="{{ i.tooltipDecr }}"/>
                        <input type="hidden" class="tooltip-icon" value="{{ i.uriIcon }}"/>
                        <input type="checkbox" name="widget" class="checkbox widget" id="{{ i.reportId }}"/>
                        <label for="{{ i.reportId }}" class="label">{{ i.reportDescr}}</label>
                    </div>
                {% endfor %}
            </fieldset>
        </div>

startbootstrap/templates/downtime_reasons_change_template.html
{% load i18n %}
<form action="" method="" id="custom-report-form" accept-charset="utf-8">
    {% csrf_token %}
            <label for="machine-reason">{% trans "Machine Name:" %}</label>
            <input type="tetxt" class="form-control" id="machine-reason" disabled>
            <label for="startDttm-reason">{% trans "Start Date Time:" %}</label>
            <input type="tetxt" class="form-control" id="startDttm-reason" disabled>
            <label for="current-reason">{% trans "Current Reason:" %}</label>
            <input type="text" class="form-control" id="current-reason" disabled>
            <br/>
            <label for="new-reason">{% trans "New Reason:" %}</label>
            <div class="form-group">
                <select class="form-control" id="new-reason">
                    <option disabled selected>{% trans "choose the new reason" %}</option>
                    <option value="{{ reason.reasonId}}" name="{{ reason.reasonId}}" class="plant-reason">{{ reason.reasonDescr}}</option>
                </select>
            </div>
</form>

startbootstrap/templates/favorites_selection_template.html
{% load i18n %}
<form action="" method="" id="custom-report-form" accept-charset="utf-8">
    {% csrf_token %}
    <div class="row">
            <div class="col-md-12">
                <div id="report-alert" class="alert alert-success hidden">
                </div>
            </div>
        </div>
    <div class="row">
        <div class="col-md-6">
            <div class="form-group">
                <label for="custom-report">{% trans "Custom Report" %}</label>
                <input type="hidden" id="query-id" value="{{ query }}"/>
                <select class="form-control" id="custom-report">
                    <option disabled selected>{% trans "choose your report" %}</option>
                    {% for custom_report in custom_report_list %}
                        <option value="{{ custom_report.id}}" name="{{ custom_report.id}}">{{ custom_report.name}}</option>
                    {% endfor %}
                </select>
            </div>
            <div class="form-group">
                <button type="button" class="btn btn-default" id="sync_custom_report" onclick="sync_user_custom_report()">{% trans "Load Report" %}</button>
            </div>
        </div>
        <div class="col-md-6">
            <div class="form-group">
                <input type="hidden" id="custom-report-parent">
                <label for="custom-report-name">{% trans "New report name" %}</label>
                <input type="text" class="form-control" id="custom-report-name" placeholder="Define report name" required>
            </div>
            <div class="form-group">
                <button type="button" class="btn btn-default" id="save-report" onclick="create_custom_report()">{% trans "Save as new report" %}</button>
            </div>
        </div>
    </div>
</form>

startbootstrap/templates/filter_cards.html
        <div class="row">
          <div class="col-xl-3 col-sm-6 mb-3">
            <div class="card text-white bg-primary o-hidden h-100">
              <div class="card-body">
                <div class="card-body-icon">
                  <i class="fa fa-fw fa-comments"></i>
                </div>
                <div class="mr-5">
                  Widgets!
                </div>
              </div>
              <a href="#" class="card-footer text-white clearfix small z-1" data-toggle="modal" data-target="#widgetSelection">
                <span class="float-left">View Details</span>
                <span class="float-right">
                  <i class="fa fa-angle-right"></i>
                </span>
              </a>
            </div>
          </div>
          <!--<div class="modal fade" id="widgetSelection" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
              <div class="modal-dialog" role="document">
                <div class="modal-content">
                  <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Widget Selection</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                      <span aria-hidden="true">&times;</span>
                    </button>
                  </div>
                  <div class="modal-body">
                    {% include 'widget_selection_template.html' %}
                  </div>
                  <div class="modal-footer">
                      <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
                      <button type="button" class="btn btn-primary" data-dismiss="modal" value="widgetModal">OK</button>
                  </div>
                </div>
              </div>
           </div>-->
          <div class="col-xl-3 col-sm-6 mb-3">
            <div class="card text-white bg-warning o-hidden h-100">
              <div class="card-body">
                <div class="card-body-icon">
                  <i class="fa fa-fw fa-list"></i>
                </div>
                <div class="mr-5">
                  Calendar!
                </div>
              </div>
              <a href="#" class="card-footer text-white clearfix small z-1" data-toggle="modal" data-target="#calendarSelection">
                <span class="float-left">View Details</span>
                <span class="float-right">
                  <i class="fa fa-angle-right"></i>
                </span>
              </a>
            </div>
          </div>
          <!--<div class="modal fade" id="calendarSelection" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
              <div class="modal-dialog" role="document">
                <div class="modal-content">
                  <div class="modal-header">
                    <h5 class="modal-title" id="calendarModalLabel">Calendar Selection</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                      <span aria-hidden="true">&times;</span>
                    </button>
                  </div>
                  <div class="modal-body">
                    {% include 'calendar_template.html' %}
                  </div>
                  <div class="modal-footer">
                      <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
                      <button type="button" class="btn btn-primary" data-dismiss="modal">OK</button>
                  </div>
                </div>
              </div>
          </div>-->
          <div class="col-xl-3 col-sm-6 mb-3">
            <div class="card text-white bg-success o-hidden h-100">
              <div class="card-body">
                <div class="card-body-icon">
                  <i class="fa fa-fw fa-shopping-cart"></i>
                </div>
                <div class="mr-5">
                  Machines!
                </div>
              </div>
              <a href="#" class="card-footer text-white clearfix small z-1" data-toggle="modal" data-target="#machinesSelection">
                <span class="float-left">View Details</span>
                <span class="float-right">
                  <i class="fa fa-angle-right"></i>
                </span>
              </a>
            </div>
          </div>
          <!--<div class="modal fade" id="machinesSelection" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
              <div class="modal-dialog  modal-lg" role="document">
                <div class="modal-content">
                  <div class="modal-header">
                    <h5 class="modal-title" id="machinesModalLabel">Machines Selection</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                      <span aria-hidden="true">&times;</span>
                    </button>
                  </div>
                  <div class="modal-body">
                    {% include 'machines_selection_template.html' %}
                  </div>
                  <div class="modal-footer">
                      <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
                      <button type="button" class="btn btn-primary" data-dismiss="modal">OK</button>
                  </div>
                </div>
              </div>
          </div>-->
          <div class="col-xl-3 col-sm-6 mb-3">
            <div class="card text-white bg-danger o-hidden h-100">
              <div class="card-body">
                <div class="card-body-icon">
                  <i class="fa fa-fw fa-support"></i>
                </div>
                <div class="mr-5">
                  Favorites!
                </div>
              </div>
              <a href="#" class="card-footer text-white clearfix small z-1" data-toggle="modal" data-target="#favoritesSelection">
                <span class="float-left">View Details</span>
                <span class="float-right">
                  <i class="fa fa-angle-right"></i>
                </span>
              </a>
            </div>
          </div>
          <!--<div class="modal fade" id="favoritesSelection" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
              <div class="modal-dialog" role="document">
                <div class="modal-content">
                  <div class="modal-header">
                    <h5 class="modal-title" id="favoritesModalLabel">Favorites Selection</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                      <span aria-hidden="true">&times;</span>
                    </button>
                  </div>
                  <div class="modal-body">
                   {% include 'favorites_selection_template.html' %}
                  </div>
                  <div class="modal-footer">
                      <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
                      <button type="button" class="btn btn-primary" data-dismiss="modal">OK</button>
                  </div>
                </div>
              </div>
          </div>-->
        </div>

startbootstrap/templates/index.html
{% extends 'base.html' %} {% load staticfiles %} {% load i18n %}
{% trans "Home" as the_home %}
{% block title %}{{ the_home }}{% endblock %}
{% block head %}
{% endblock %}
{% block page-title %}{{ the_home }}{% endblock %}
{% block main-content %}<img src="{% static 'images/iot_bg5.jpg' %}" alt="" />{% endblock %}

startbootstrap/templates/machine_status_widget.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

startbootstrap/templates/plant_reasons_list.html
{% for reason in reasons_list %}
    <option value="{{ reason.reasonId}}" name="{{ reason.reasonId}}">{{ reason.reasonDescr}}</option>
{% endfor %}